name: Backend Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-multipart

      - name: Run tests
        working-directory: ./backend
        env:
          REDIS_URL: redis://localhost:6379/0
          PYTHONPATH: ${{ github.workspace }}/backend
        run: |
          echo "Running tests with PYTHONPATH=$PYTHONPATH"
          pytest -q
